name: Laravel

on: pull_request

jobs:
  laravel-checks:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'SKIP ACTIONS')"
    container: thomasowow/laravel-php:7.4

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: laravel
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --tmpfs="/var/lib/mysql"

    steps:
      - uses: actions/checkout@v2

      - name: Cache vendor
        uses: actions/cache@v2
        env:
          cache-name: cache-vendor
        with:
          path: ./vendor
          key: vendor-${{ env.cache-name }}-${{ hashFiles('./composer.lock') }}
          restore-keys: vendor-${{ env.cache-name }}

      - name: Composer
        run: |
          composer install --no-scripts

      - name: Phpunit
        env:
          DB_HOST: mysql
        run: |
          vendor/bin/phpunit

      - name: Code sniffer
        run: |
          vendor/bin/phpcs -s